In [1]:
import numpy as np

In [2]:
np.arange(15).shape(3,5)

TypeError: 'tuple' object is not callable

In [3]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
a.size

15